const REQUEST_PATH_URL_SHOERTENER = "url-shortener";

const REQUEST_PATH_URL_SHOERTENER_ALL = "url-shortener/all";

const REQUEST_PATH_URL_KEY = "url-key";

const REQUEST_PATH_PRODUCT_NAME_ALL = "product-name/all";

const REQUEST_PATH_SHORTLINK = "s";

export { REQUEST_PATH_URL_SHOERTENER, REQUEST_PATH_URL_SHOERTENER_ALL, REQUEST_PATH_URL_KEY, REQUEST_PATH_PRODUCT_NAME_ALL, REQUEST_PATH_SHORTLINK };
